name: Linting, testing, building

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
jobs:
  pipelint:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]
    steps:
      - uses: actions/checkout@v2
      - name: Staring Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: install modules
        run: npm install
      - name: build prod project
        run: npm run build:prod
      - name: linting TS
        run: npm run lint:ts
        if: always()
      - name: linting SCSS
        run: npm run lint:scss
        if: always()
      - name: unit testing
        run: npm run test:unit
        if: always()
  ui:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]
    steps:
      - uses: actions/checkout@v2
      - name: Staring Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: install modules
        run: npm install
      - name: build prod project
        run: npm run build:prod
      - name: build storybook
        run: npm run storybook:build
        if: always()
      - name: loki test screenshot
        run: npm run test:ui:ci
        if: always()
      - name: make report
        uses: actions/upload-artifact@v3
        with:
          name: my-artifact
          path: .loki/
        if: failure()


